# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f309cf57877bcb5db46a4ced75397bd453351bd9888376992160727ed2cd8b1763ac32eb2c34657d0b78cedd2b92f18af551516e4d7156cd59e92719f00c7da2

test:
  secret_key_base: 03ae7a60c99154542994d871a5e072bcbf8817955a29eba76d1366ff17075f11f3a641349ea93304ed2e5835a238b6c04f393132dd217ecdcde4e7063c36cafe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
